# -*- coding: UTF-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['scpgui.py']
APP_NAME = "SCP"
DATA_FILES = []
OPTIONS = {
'argv_emulation': True,
'iconfile': 'SCP.icns',
'plist': {
    'CFBundleName': APP_NAME,
    'CFBundleDisplayName': APP_NAME,
    'CFBundleGetInfoString': "Checkes steam community item price, alarm when price changes.",
    'CFBundleIdentifier': "com.yilinhu.scp",
    'CFBundleVersion': "0.1.0",
    'CFBundleShortVersionString': "0.1.0",
    'NSHumanReadableCopyright': "Copyright 2019, Yilin Hu"
}
}
setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
